// <auto-generated />
namespace Harvin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mesasócompedidos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mesasócompedidos));
        
        string IMigrationMetadata.Id
        {
            get { return "201802042146032_mesa só com pedidos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
